"""Tests for Bonsai API models."""

import pytest
from pydantic import ValidationError

from bonsai_libs.api_client.bonsai.models import CreateGroupInput, GroupResponse


def test_create_group_input_does_not_require_group_id():
    """Group IDs are generated by the Bonsai API when groups are created."""
    group = CreateGroupInput(display_name="Test group")

    assert group.display_name == "Test group"
    assert "group_id" not in group.model_dump()


def test_group_response_requires_group_id():
    """Responses still expose the server-generated group ID."""
    with pytest.raises(ValidationError):
        GroupResponse(
            display_name="Test group",
            sample_count=0,
            created_at="2026-09-14T00:00:00Z",
            modified_at="2026-09-14T00:00:00Z",
        )
